# Estsdistica aplicada
## Lizbeth Ramos Saucedo 
### Segunda sesion 
#### 27 de enero 2023 

In [3]:
7 > 5

True

In [4]:
7 > 10

False

In [5]:
7>5 & 7>10

False

In [7]:
7+5

12

In [8]:
10-3

7

In [9]:
5*2

10

In [10]:
10/2

5.0

In [11]:
3**2

9

In [13]:
pow(3, 2)


9

In [16]:
alumno1 = ['Juan', 'Perez', 23] 

In [17]:
type(alumno1)

list

In [18]:
estadistica_g4 = ['Juan','Raul','Jimena', 'Alejandra']

In [19]:
estadistica_g4

['Juan', 'Raul', 'Jimena', 'Alejandra']

In [20]:
estadistica_g4[2]

'Jimena'

In [21]:
estadistica_g4[0]

'Juan'

In [22]:
estadistica_g4[0], estadistica_g4[2]

('Juan', 'Jimena')

In [23]:
estadistica_g4[0:3]

['Juan', 'Raul', 'Jimena']

In [24]:
estadistica_g4[:]

['Juan', 'Raul', 'Jimena', 'Alejandra']

In [29]:
estadistica_g4.append('Jaime') ##apend agrega un elemento a la lista 

In [28]:
estadistica_g4

['Juan', 'Raul', 'Jimena', 'Alejandra', 'Jaime']

In [30]:
estadistica_g4.remove('Jimena')

In [31]:
estadistica_g4

['Juan', 'Raul', 'Alejandra', 'Jaime', 'Jaime']

In [32]:
estadistica_g4.remove('Jaime')

In [33]:
estadistica_g4

['Juan', 'Raul', 'Alejandra', 'Jaime']

In [34]:
len(estadistica_g4)

4

In [35]:
conteo_de_lista=len(estadistica_g4)

In [36]:
conteo_de_lista

4

In [38]:
pip install yfinance

Note: you may need to restart the kernel to use updated packages.


In [40]:
import yfinance as yf

In [42]:
import numpy as np

In [60]:
numeros =[25.7, 8, 10]

In [61]:
type(numeros)

list

In [62]:
numeros= np.array(numeros)

In [63]:
type(numeros)

numpy.ndarray

In [64]:
np.sum(numeros)

43.7

In [65]:
np.prod(numeros)

2056.0

In [66]:
np.mean(numeros) #calcula media 

14.566666666666668

In [67]:
np.var(numeros) #calcula varianza poblacional /sigma cuadrada

62.642222222222216

In [68]:
np.var(numeros,ddof=1)  #varianza muestral

93.96333333333332

In [70]:
np.std(numeros) #desviacion estandar poblacional

7.9146839622452525

In [71]:
np.std(numeros, ddof=1) #desviacion estandar muestral

9.693468591445134

In [72]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
np.arange(7,15)

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [74]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [75]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [76]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [77]:
np.full(6,9)

array([9, 9, 9, 9, 9, 9])

In [80]:
np.random.randint(0,10,2)

array([8, 6])

In [86]:
np.random.seed(5) #fijar semillas para que los numeros alestorios sean iguales y alguin mas lo pueda replicar
aleatoriosu= np.random.randint(10,30,8)
#aleatorios que vienen de una uniforme 


In [87]:
aleatoriosu

array([13, 24, 25, 16, 26, 19, 18, 14])

In [89]:
aleatoriosu= np.sort(aleatoriosu)

In [90]:
aleatoriosu

array([13, 14, 16, 18, 19, 24, 25, 26])

In [91]:
aleatoriosu[2]

16

In [93]:
aleatoriosu[[2,5]]

array([16, 24])

In [94]:
aleatoriosu>15

array([False, False,  True,  True,  True,  True,  True,  True])

In [95]:
aleatoriosu[aleatoriosu>15]

array([16, 18, 19, 24, 25, 26])

In [96]:
num2 = [10,8,20]

In [97]:
num2 = np.array(num2)

In [98]:
np.mean(num2)

12.666666666666666

In [99]:
num2.mean()

12.666666666666666

In [102]:
round(np.mean(np.sum(num2)))

38

In [104]:
num2.sum().mean().round()

38.0

In [105]:
numeros = [1.23, 2.45578, 5.66888785]

In [106]:
round(np.mean(np.array(numeros)),2)

3.12

In [107]:
np.array(numeros).mean().round(2)

3.12